stages:
- name: Test
  steps:
  - runScriptConfig:
      image: maven:3.6-jdk-8
      shellScript: |-
        mvn test
- name: Publish
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: cloud/devops-tenants:${CICD_EXECUTION_SEQUENCE}
- name: Deploy
  steps:
  - applyYamlConfig:
      path: ./deploy/deployment-dev.yaml
  - applyYamlConfig:
      path: ./deploy/deployment-staging.yaml
  - applyYamlConfig:
      path: ./deploy/deployment-prod.yaml
    when:
      branch:
        include:
        - master
      event:
        include:
        - push
timeout: 60
notification: {}
