apiVersion: v1
kind: Service
metadata:
  name: tenants-service
  namespace: staging
spec:
  selector:
    app: tenants-service
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: tenants-service
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tenants-service
  namespace: staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tenants-service
  template:
    metadata:
      labels:
        app: tenants-service
    spec:
      imagePullSecrets:
        - name: pipeline-docker-registry
      nodeName: prod-node-1
      containers:
        - name: tenants-service
          image: ${CICD_IMAGE}:${CICD_EXECUTION_SEQUENCE}
          env:
            - name: APP_ENVIRONMENT
              value: 'staging'
            - name: KAFKA_PREFIX
              value: staging
            - name: KAFKA_HOST
              value: kafka.kafka
            - name: KAFKA_PORT
              value: '9094'
          envFrom:
            - secretRef:
                name: -tenants-staging-db-credentials
                optional: false
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: tenants-ingress
  namespace: staging
spec:
  rules:
    - host: tenants.staging.116.203.92.21.xip.io
      http:
        paths:
          - backend:
              serviceName: tenants-service
              servicePort: 8080
            path: /api/tenant
  tls:
    - hosts:
        - tenants.staging.116.203.92.21.xip.io
---


